// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaKCLjvMl0FSjj9cVVUrbQKM23waNWfdU',
    appId: '1:876296514345:web:85456e6a4fa9fd6f462538',
    messagingSenderId: '876296514345',
    projectId: 'kiwimath-801c1',
    authDomain: 'kiwimath-801c1.firebaseapp.com',
    storageBucket: 'kiwimath-801c1.firebasestorage.app',
    measurementId: 'G-23JK4JYF50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnKemVJ_qPn4LTUuN5JhCqK1FQ-ms5Oug',
    appId: '1:876296514345:android:36648fe480c848a7462538',
    messagingSenderId: '876296514345',
    projectId: 'kiwimath-801c1',
    storageBucket: 'kiwimath-801c1.firebasestorage.app',
  );

}